#!/bin/sh

ndk=$(awk -F= '/^ndk.dir=/{print$2}' ../local.properties)
api=21
toolchain=$ndk/toolchains/llvm/prebuilt/linux-x86_64/bin

triple() {
	case $1 in
	arm)	echo armv7a-linux-androideabi ;;
	arm64)	echo aarch64-linux-android ;;
	x86)	echo i686-linux-android ;;
	x86_64)	echo x86_64-linux-android ;;
	esac
}

agcc() {
	local flags

	case $AGCCARCH in
	arm)	flags='-mfloat-abi=softfp -march=armv7-a -mtune=cortex-a9' ;;
	arm64)	flags='-march=armv8-a' ;;
	x86*)	flags='-march=atom' ;;
	esac

	$toolchain/$(triple $AGCCARCH)$api-clang -fPIE -pie -Ofast -fcommon $flags "$@"
}

mkdir -p src/main/assets
for i in arm arm64 x86 x86_64; do
	AGCCARCH=$i
	agcc -c src/main/c/dry.c -o /tmp/dry$$.o -Wall
	agcc src/main/c/dry.c /tmp/dry$$.o -o src/main/assets/dry-$i -Wall -DPASS2
	rm -f /tmp/dry$$.o
	$toolchain/llvm-strip -s -R.comment src/main/assets/dry-$i
done
